#!/usr/bin/env node

import crypto from "node:crypto";
import {execFileSync} from "node:child_process";
import {existsSync, mkdirSync, readdirSync, readFileSync, realpathSync, renameSync, writeFileSync} from "node:fs";
import path from "node:path";

import {isMainModule} from "../../_shared/scripts/is-main-module.mjs";
import {resolveArtifactCacheRoot} from "../../_shared/scripts/artifact-path.mjs";
import {buildChangeInventory, getWorktreeFingerprint} from "../../_shared/scripts/change-inventory.mjs";
import {detectSecrets} from "../../_shared/scripts/secret-detector.mjs";

export const JOB_VERSION = 1;
export const PROVIDER = "claude";
export const ENVELOPE_STATUSES = Object.freeze(["COMPLETE", "INCOMPLETE", "BLOCKED", "STALE"]);
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const INPUT_FILES = Object.freeze(["inventory.json", "staged.diff", "unstaged.diff", "untracked.txt", "requirements.md", "prompt.md"]);

export class JobError extends Error {
    constructor(code, message, details = {}) {
        super(message);
        this.code = code;
        this.details = details;
    }
}

function sha256(value) {
    return crypto.createHash("sha256").update(value).digest("hex");
}

function git(args, cwd, execFile) {
    return String(execFile("git", args, {cwd, encoding: "utf8", maxBuffer: 256 * 1024 * 1024, stdio: ["ignore", "pipe", "pipe"]}));
}

function writeAtomic(filePath, content) {
    const temporary = `${filePath}.${process.pid}.tmp`;
    writeFileSync(temporary, content);
    renameSync(temporary, filePath);
}

function readJson(filePath, code) {
    try {
        return JSON.parse(readFileSync(filePath, "utf8"));
    } catch (error) {
        throw new JobError(code, `Cannot read JSON from ${filePath}: ${error.message}`);
    }
}

function canonicalPath(value) {
    const resolved = path.resolve(value);
    return existsSync(resolved) ? realpathSync(resolved) : resolved;
}

function repositoryRoot(cwd, execFile) {
    try {
        return realpathSync(git(["rev-parse", "--show-toplevel"], cwd, execFile).trim());
    } catch (error) {
        throw new JobError("NOT_A_REPOSITORY", `Not a git repository: ${cwd}`, {cause: error.message});
    }
}

export function readSnapshot(repo, execFile = execFileSync) {
    let head;
    try {
        head = git(["rev-parse", "--verify", "HEAD"], repo, execFile).trim();
    } catch (error) {
        throw new JobError("NO_HEAD", "Repository has no HEAD commit.", {cause: error.message});
    }
    return {head, combined_sha256: getWorktreeFingerprint({cwd: repo, execFile}).combined_sha256};
}

function jobsRoot(repo) {
    return path.join(resolveArtifactCacheRoot(repo), "claude-review");
}

export function jobDirectory(repo, jobId) {
    if (typeof jobId !== "string" || !UUID_PATTERN.test(jobId)) {
        throw new JobError("INVALID_JOB_ID", "job_id must be a lowercase UUID generated by the parent.");
    }
    return path.join(jobsRoot(repo), jobId);
}

function splitDiffByFile(diff) {
    const chunks = [];
    for (const part of diff.split(/^(?=diff --git )/m)) {
        if (part.trim() === "") { continue; }
        const header = part.match(/^diff --git a\/(.+?) b\/(.+)$/m);
        chunks.push({path: header ? header[2] : null, text: part});
    }
    return chunks;
}

function redactSensitive(diff, surface, omitted) {
    return splitDiffByFile(diff)
        .filter((chunk) => {
            if (detectSecrets({diff: chunk.text}).length === 0) { return true; }
            omitted.push({surface, path: chunk.path});
            return false;
        })
        .map((chunk) => chunk.text)
        .join("");
}

function unconfirmedStops(repo) {
    const root = jobsRoot(repo);
    if (!existsSync(root)) { return []; }
    return readdirSync(root)
        .map((name) => path.join(root, name, "job.json"))
        .filter((jobPath) => existsSync(jobPath))
        .filter((jobPath) => readJson(jobPath, "INVALID_JOB").outcome?.reason === "TIMEOUT_STOP_UNCONFIRMED");
}

function renderPrompt(job, relativeDirectory) {
    const file = (name) => `${relativeDirectory}/${name}`;
    const context = job.context_refs.length === 0
        ? "- none supplied"
        : job.context_refs.map((ref) => `- ${ref.path}`).join("\n");
    return `You are a read-only code-review executor for one job from a coordinating OpenCode agent.

Invoke the native Skill \`code-review\` with \`execution_role: executor\` and target \`code\`, then follow it.
Review the working-tree snapshot HEAD=${job.snapshot.head}, combined_sha256=${job.snapshot.combined_sha256}.

Supplied inputs (repository-relative):
- change inventory: ${file("inventory.json")}
- staged diff: ${file("staged.diff")}
- unstaged diff: ${file("unstaged.diff")}
- untracked paths: ${file("untracked.txt")}
- requirements: ${file("requirements.md")}
- context references:
${context}
${job.omitted_sensitive.length > 0 ? `- omitted as sensitive (coverage limit): ${job.omitted_sensitive.map((item) => `${item.surface}:${item.path}`).join(", ")}\n` : ""}
Do not edit files, run shell commands, start agents or Paseo sessions, or invoke skills other than code-review.
If essential input is missing, return status INCOMPLETE and name it in the report.

Return ONLY one JSON object, with no text around it:
{"version":${JOB_VERSION},"job_id":"${job.job_id}","snapshot":{"head":"${job.snapshot.head}","combined_sha256":"${job.snapshot.combined_sha256}"},"status":"COMPLETE|INCOMPLETE|BLOCKED|STALE","report_markdown":"<code-review Output format report>"}
The status describes whether the review work finished; it is not a merge verdict.
`;
}

export function prepareJob(options, {cwd = process.cwd(), execFile = execFileSync, now = new Date()} = {}) {
    const repo = repositoryRoot(cwd, execFile);
    const directory = jobDirectory(repo, options.jobId);
    if (typeof options.model !== "string" || options.model.trim() === "") {
        throw new JobError("INVALID_PARAMETERS", "An explicit Opus model is required.");
    }
    if (typeof options.thinking !== "string" || options.thinking.trim() === "") {
        throw new JobError("INVALID_PARAMETERS", "An explicit thinking level is required.");
    }
    const timeoutSeconds = Number(options.timeoutSeconds);
    if (!Number.isInteger(timeoutSeconds) || timeoutSeconds <= 0) {
        throw new JobError("INVALID_PARAMETERS", "timeout_seconds must be a positive integer.");
    }
    if (typeof options.requirements !== "string" || !existsSync(options.requirements)) {
        throw new JobError("INVALID_PARAMETERS", "A requirements file is required.");
    }
    const blocking = unconfirmedStops(repo);
    if (blocking.length > 0) {
        throw new JobError("UNCONFIRMED_STOP_PENDING", "A previous review session timed out without a confirmed stop.", {jobs: blocking});
    }
    if (existsSync(directory)) {
        throw new JobError("JOB_EXISTS", "This job_id was already prepared; a job has exactly one attempt.");
    }

    const contextRefs = (options.context ?? []).map((reference) => {
        const absolute = canonicalPath(path.resolve(cwd, reference));
        const relative = path.relative(repo, absolute);
        if (relative.startsWith("..") || path.isAbsolute(relative) || !existsSync(absolute)) {
            throw new JobError("INVALID_CONTEXT_REF", `Context reference must be an existing file inside the repository: ${reference}`);
        }
        return {path: relative, sha256: sha256(readFileSync(absolute))};
    });

    const snapshot = readSnapshot(repo, execFile);
    const inventory = buildChangeInventory({cwd: repo, execFile, now});
    const omitted = [];
    const diffArgs = ["--no-color", "--no-ext-diff", "--no-renames", "--"];
    const staged = redactSensitive(git(["diff", "--cached", ...diffArgs], repo, execFile), "staged", omitted);
    const unstaged = redactSensitive(git(["diff", ...diffArgs], repo, execFile), "unstaged", omitted);
    const untracked = inventory.files.filter((file) => file.untracked).map((file) => file.path);

    mkdirSync(directory, {recursive: true});
    const job = {
        version: JOB_VERSION,
        job_id: options.jobId,
        repo,
        created_at: now.toISOString(),
        snapshot,
        parameters: {provider: PROVIDER, model: options.model, thinking: options.thinking, timeout_seconds: timeoutSeconds},
        inputs: {},
        context_refs: contextRefs,
        omitted_sensitive: omitted,
        session: null,
        outcome: null,
    };
    const relativeDirectory = path.relative(repo, directory);
    const artifacts = {
        "inventory.json": `${JSON.stringify(inventory, null, 2)}\n`,
        "staged.diff": staged,
        "unstaged.diff": unstaged,
        "untracked.txt": untracked.map((item) => `${item}\n`).join(""),
        "requirements.md": readFileSync(options.requirements),
        "prompt.md": renderPrompt(job, relativeDirectory),
    };
    for (const name of INPUT_FILES) {
        writeFileSync(path.join(directory, name), artifacts[name]);
        job.inputs[name] = sha256(artifacts[name]);
    }
    const jobPath = path.join(directory, "job.json");
    writeAtomic(jobPath, `${JSON.stringify(job, null, 2)}\n`);
    const afterWrite = readSnapshot(repo, execFile);
    if (afterWrite.head !== snapshot.head || afterWrite.combined_sha256 !== snapshot.combined_sha256) {
        throw new JobError("CACHE_NOT_IGNORED", "Writing the job changed the reviewed snapshot; CACHE_PATH must be ignored by git.", {job_path: path.relative(repo, jobPath)});
    }
    return {
        job_path: path.relative(repo, jobPath),
        prompt_path: path.join(relativeDirectory, "prompt.md"),
        launch: {provider: PROVIDER, model: job.parameters.model, thinking: job.parameters.thinking, cwd: repo, wait_timeout_seconds: timeoutSeconds},
        omitted_sensitive: omitted,
    };
}

function loadJob(jobPath) {
    const job = readJson(jobPath, "INVALID_JOB");
    if (job?.version !== JOB_VERSION || typeof job.job_id !== "string" || !job.snapshot) {
        throw new JobError("INVALID_JOB", "Unsupported or malformed job file.");
    }
    jobDirectory(job.repo, job.job_id);
    return job;
}

function saveJob(jobPath, job) {
    writeAtomic(jobPath, `${JSON.stringify(job, null, 2)}\n`);
}

function sessionIdentity(inspect) {
    return {
        id: inspect?.Id ?? null,
        parent_id: inspect?.ParentAgentId ?? null,
        provider: inspect?.Provider ?? null,
        model: inspect?.Model ?? null,
        thinking: inspect?.Thinking ?? null,
        cwd: typeof inspect?.Cwd === "string" ? canonicalPath(inspect.Cwd) : null,
    };
}

function identityMismatches(actual, expected) {
    return Object.keys(expected).filter((key) => actual[key] !== expected[key]);
}

export function bindSession({jobPath, inspect, parentId}) {
    const job = loadJob(jobPath);
    if (job.session !== null) {
        throw new JobError("SESSION_ALREADY_BOUND", "This job already has a session; no second attempt is allowed.");
    }
    if (typeof parentId !== "string" || parentId.trim() === "") {
        throw new JobError("INVALID_PARAMETERS", "The coordinating agent id (parent) is required.");
    }
    const identity = sessionIdentity(inspect);
    const expected = {
        parent_id: parentId,
        provider: job.parameters.provider,
        model: job.parameters.model,
        thinking: job.parameters.thinking,
        cwd: job.repo,
    };
    const mismatches = identityMismatches(identity, expected);
    if (identity.id === null || mismatches.length > 0) {
        throw new JobError("SESSION_MISMATCH", "The launched session does not match the job.", {fields: identity.id === null ? ["id"] : mismatches});
    }
    job.session = identity;
    saveJob(jobPath, job);
    return {session: identity};
}

function inputChanges(job, jobPath) {
    const directory = path.dirname(jobPath);
    const changed = INPUT_FILES.filter((name) => {
        const filePath = path.join(directory, name);
        return !existsSync(filePath) || sha256(readFileSync(filePath)) !== job.inputs[name];
    });
    for (const ref of job.context_refs) {
        const filePath = path.join(job.repo, ref.path);
        if (!existsSync(filePath) || sha256(readFileSync(filePath)) !== ref.sha256) { changed.push(ref.path); }
    }
    return changed;
}

export function parseEnvelope(text) {
    let envelope;
    try {
        envelope = JSON.parse(String(text).trim());
    } catch {
        return {ok: false, errors: ["envelope is not a single JSON object"]};
    }
    const errors = [];
    if (envelope === null || typeof envelope !== "object" || Array.isArray(envelope)) {
        return {ok: false, errors: ["envelope must be an object"]};
    }
    if (envelope.version !== JOB_VERSION) { errors.push("version must be 1"); }
    if (typeof envelope.job_id !== "string") { errors.push("job_id is required"); }
    if (typeof envelope.snapshot?.head !== "string" || typeof envelope.snapshot?.combined_sha256 !== "string") {
        errors.push("snapshot.head and snapshot.combined_sha256 are required");
    }
    if (!ENVELOPE_STATUSES.includes(envelope.status)) { errors.push("status is not supported"); }
    if (typeof envelope.report_markdown !== "string" || envelope.report_markdown.trim() === "") {
        errors.push("report_markdown must be non-empty text");
    }
    return errors.length === 0 ? {ok: true, envelope} : {ok: false, errors};
}

function decide(job, decision) {
    return {job_id: job.job_id, ...decision};
}

export function acceptResult({jobPath, envelopeText, inspect}, {execFile = execFileSync} = {}) {
    const job = loadJob(jobPath);
    if (job.session === null) {
        return decide(job, {decision: "REJECTED", reason: "SESSION_NOT_BOUND"});
    }
    const changed = inputChanges(job, jobPath);
    if (changed.length > 0) {
        return decide(job, {decision: "REJECTED", reason: "INPUT_CHANGED", details: changed});
    }
    const identity = sessionIdentity(inspect);
    const mismatches = identityMismatches(identity, job.session);
    if (mismatches.length > 0) {
        return decide(job, {decision: "REJECTED", reason: "SESSION_MISMATCH", details: mismatches});
    }
    if (Array.isArray(inspect?.PendingPermissions) && inspect.PendingPermissions.length > 0) {
        return decide(job, {decision: "BLOCKED", reason: "PERMISSION_PENDING"});
    }
    const parsed = parseEnvelope(envelopeText);
    if (!parsed.ok) {
        return decide(job, {decision: "REJECTED", reason: "REPORT_INVALID", details: parsed.errors});
    }
    const {envelope} = parsed;
    if (envelope.job_id !== job.job_id) {
        return decide(job, {decision: "REJECTED", reason: "JOB_MISMATCH"});
    }
    if (envelope.snapshot.head !== job.snapshot.head || envelope.snapshot.combined_sha256 !== job.snapshot.combined_sha256) {
        return decide(job, {decision: "REJECTED", reason: "SNAPSHOT_MISMATCH"});
    }
    const current = readSnapshot(job.repo, execFile);
    if (current.head !== job.snapshot.head || current.combined_sha256 !== job.snapshot.combined_sha256) {
        return decide(job, {decision: "STALE", reason: "SNAPSHOT_CHANGED"});
    }
    if (envelope.status === "STALE") {
        return decide(job, {decision: "STALE", reason: "EXECUTOR_REPORTED_STALE"});
    }
    return decide(job, {decision: "ACCEPTED", status: envelope.status, report_markdown: envelope.report_markdown});
}

export function recordTimeout({jobPath, stopConfirmed}) {
    const job = loadJob(jobPath);
    job.outcome = stopConfirmed
        ? {status: "INCOMPLETE", reason: "TIMEOUT_STOPPED", retry_allowed: false}
        : {status: "BLOCKED", reason: "TIMEOUT_STOP_UNCONFIRMED", retry_allowed: false};
    saveJob(jobPath, job);
    return job.outcome;
}

function usage() {
    return `Usage:
  review-job.mjs prepare --job-id <uuid> --requirements <file> --model <id> --thinking <id> --timeout-seconds <n> [--context <file>]...
  review-job.mjs bind-session --job <job.json> --inspect <paseo-inspect.json> --parent-id <agent-id>
  review-job.mjs accept --job <job.json> --envelope <final-message.txt> --inspect <paseo-inspect.json>
  review-job.mjs record-timeout --job <job.json> --stop-confirmed <yes|no>

The helper prepares and validates one Claude review job. It never starts agents,
runs Paseo, or polls; the coordinating agent does that and passes the results in.
`;
}

function parseArgs(argv) {
    const [command, ...rest] = argv;
    const options = {command, context: []};
    for (let index = 0; index < rest.length; index += 1) {
        const key = rest[index];
        const value = rest[index + 1];
        if (!key.startsWith("--") || index + 1 >= rest.length) {
            throw new JobError("INVALID_ARGUMENTS", `Unexpected argument: ${key}`);
        }
        index += 1;
        if (key === "--context") { options.context.push(value); continue; }
        options[key.slice(2).replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())] = value;
    }
    return options;
}

function run(argv) {
    if (argv.length === 0 || argv.includes("--help") || argv.includes("-h")) {
        process.stdout.write(usage());
        return 0;
    }
    const options = parseArgs(argv);
    let result;
    if (options.command === "prepare") {
        result = prepareJob(options);
    } else if (options.command === "bind-session") {
        result = bindSession({jobPath: options.job, inspect: readJson(options.inspect, "INVALID_INSPECT"), parentId: options.parentId});
    } else if (options.command === "accept") {
        result = acceptResult({jobPath: options.job, envelopeText: readFileSync(options.envelope, "utf8"), inspect: readJson(options.inspect, "INVALID_INSPECT")});
        writeAtomic(path.join(path.dirname(options.job), "result.json"), `${JSON.stringify(result, null, 2)}\n`);
    } else if (options.command === "record-timeout") {
        if (!["yes", "no"].includes(options.stopConfirmed)) {
            throw new JobError("INVALID_ARGUMENTS", "--stop-confirmed must be yes or no.");
        }
        result = recordTimeout({jobPath: options.job, stopConfirmed: options.stopConfirmed === "yes"});
    } else {
        throw new JobError("INVALID_ARGUMENTS", `Unknown command: ${options.command}`);
    }
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
    return 0;
}

if (isMainModule(import.meta.url)) {
    try {
        process.exitCode = run(process.argv.slice(2));
    } catch (error) {
        const payload = {error: error.code ?? "UNEXPECTED", message: error.message, details: error.details ?? {}};
        process.stderr.write(`${JSON.stringify(payload)}\n`);
        process.exitCode = 1;
    }
}
